export const LENGTH_OPTIONS = [
  { label: "Laps", value: "laps" },
  { label: "Time", value: "time" },
]

export const SESSION_TIME_OPTIONS = [
  { label: "1 Min", value: "1 Min" },
  { label: "2 Min", value: "2 Mins" },
  { label: "3 Min", value: "3 Mins" },
  { label: "5 Min", value: "5 Mins" },
  { label: "10 Min", value: "10 Mins" },
  { label: "15 Min", value: "15 Mins" },
  { label: "20 Min", value: "20 Mins" },
  { label: "25 Min", value: "25 Mins" },
  { label: "30 Min", value: "30 Mins" },
  { label: "40 Min", value: "40 Mins" },
  { label: "50 Min", value: "50 Mins" },
  { label: "60 Min", value: "60 Mins" },
  { label: "90 Min", value: "90 Mins" },
  { label: "2 Hr", value: "2 Hrs" },
  { label: "3 Hr", value: "3 Hrs" },
  { label: "4 Hr", value: "4 Hrs" },
  { label: "5 Hr", value: "5 Hrs" },
  { label: "6 Hr", value: "6 Hrs" },
  { label: "7 Hr", value: "7 Hrs" },
  { label: "8 Hr", value: "8 Hrs" },
  { label: "9 Hr", value: "9 Hrs" },
  { label: "10 Hr", value: "10 Hrs" },
  { label: "11 Hr", value: "11 Hrs" },
  { label: "12 Hr", value: "12 Hrs" },
  { label: "13 Hr", value: "13 Hrs" },
  { label: "14 Hr", value: "14 Hrs" },
  { label: "15 Hr", value: "15 Hrs" },
  { label: "16 Hr", value: "16 Hrs" },
  { label: "17 Hr", value: "17 Hrs" },
  { label: "18 Hr", value: "18 Hrs" },
  { label: "19 Hr", value: "19 Hrs" },
  { label: "20 Hr", value: "20 Hrs" },
  { label: "21 Hr", value: "21 Hrs" },
  { label: "22 Hr", value: "22 Hrs" },
  { label: "23 Hr", value: "23 Hrs" },
  { label: "24 Hr", value: "24 Hrs" },
];
