export const LENGTH_OPTIONS = [
  { label: "Laps", value: "laps" },
  { label: "Time", value: "time" },
]

export const SESSION_TIME_OPTIONS = [
  { label: "1 Min", value: "1 Min" },
  { label: "2 Min", value: "2 Min" },
  { label: "3 Min", value: "3 Min" },
  { label: "5 Min", value: "5 Min" },
  { label: "10 Min", value: "10 Min" },
  { label: "15 Min", value: "15 Min" },
  { label: "20 Min", value: "20 Min" },
  { label: "25 Min", value: "25 Min" },
  { label: "30 Min", value: "30 Min" },
  { label: "40 Min", value: "40 Min" },
  { label: "50 Min", value: "50 Min" },
  { label: "60 Min", value: "60 Min" },
  { label: "90 Min", value: "90 Min" },
  { label: "2 Hr", value: "2 Hr" },
  { label: "3 Hr", value: "3 Hr" },
  { label: "4 Hr", value: "4 Hr" },
  { label: "5 Hr", value: "5 Hr" },
  { label: "6 Hr", value: "6 Hr" },
  { label: "7 Hr", value: "7 Hr" },
  { label: "8 Hr", value: "8 Hr" },
  { label: "9 Hr", value: "9 Hr" },
  { label: "10 Hr", value: "10 Hr" },
  { label: "11 Hr", value: "11 Hr" },
  { label: "12 Hr", value: "12 Hr" },
  { label: "13 Hr", value: "13 Hr" },
  { label: "14 Hr", value: "14 Hr" },
  { label: "15 Hr", value: "15 Hr" },
  { label: "16 Hr", value: "16 Hr" },
  { label: "17 Hr", value: "17 Hr" },
  { label: "18 Hr", value: "18 Hr" },
  { label: "19 Hr", value: "19 Hr" },
  { label: "20 Hr", value: "20 Hr" },
  { label: "21 Hr", value: "21 Hr" },
  { label: "22 Hr", value: "22 Hr" },
  { label: "23 Hr", value: "23 Hr" },
  { label: "24 Hr", value: "24 Hr" },
];
