export const LENGTH_OPTIONS = [
  { label: "Laps", value: "laps" },
  { label: "Time", value: "time" },
]

export const SESSION_TIME_OPTIONS = [
  { label: "1 Min", value: "1 Min" },
  { label: "2 Mins", value: "2 Mins" },
  { label: "3 Mins", value: "3 Mins" },
  { label: "5 Mins", value: "5 Mins" },
  { label: "10 Mins", value: "10 Mins" },
  { label: "15 Mins", value: "15 Mins" },
  { label: "20 Mins", value: "20 Mins" },
  { label: "25 Mins", value: "25 Mins" },
  { label: "30 Mins", value: "30 Mins" },
  { label: "40 Mins", value: "40 Mins" },
  { label: "50 Mins", value: "50 Mins" },
  { label: "60 Mins", value: "60 Mins" },
  { label: "90 Mins", value: "90 Mins" },
  { label: "2 Hrs", value: "2 Hrs" },
  { label: "3 Hrs", value: "3 Hrs" },
  { label: "4 Hrs", value: "4 Hrs" },
  { label: "5 Hrs", value: "5 Hrs" },
  { label: "6 Hrs", value: "6 Hrs" },
  { label: "7 Hrs", value: "7 Hrs" },
  { label: "8 Hrs", value: "8 Hrs" },
  { label: "9 Hrs", value: "9 Hrs" },
  { label: "10 Hrs", value: "10 Hrs" },
  { label: "11 Hrs", value: "11 Hrs" },
  { label: "12 Hrs", value: "12 Hrs" },
  { label: "13 Hrs", value: "13 Hrs" },
  { label: "14 Hrs", value: "14 Hrs" },
  { label: "15 Hrs", value: "15 Hrs" },
  { label: "16 Hrs", value: "16 Hrs" },
  { label: "17 Hrs", value: "17 Hrs" },
  { label: "18 Hrs", value: "18 Hrs" },
  { label: "19 Hrs", value: "19 Hrs" },
  { label: "20 Hrs", value: "20 Hrs" },
  { label: "21 Hrs", value: "21 Hrs" },
  { label: "22 Hrs", value: "22 Hrs" },
  { label: "23 Hrs", value: "23 Hrs" },
  { label: "24 Hrs", value: "24 Hrs" },
];
