export const GT7_TRACKS = [
  "24 Heures du Mans Racing Circuit",
  "24 Heures du Mans Racing Circuit No Chicane",
  "Alsace - Test Course",
  "Alsace - Test Course Reverse",
  "Alsace - Village",
  "Alsace - Village Reverse",
  "Autodrome Lago Maggiore - Centre",
  "Autodrome Lago Maggiore - Centre Reverse",
  "Autodrome Lago Maggiore - East",
  "Autodrome Lago Maggiore - East End",
  "Autodrome Lago Maggiore - East End Reverse",
  "Autodrome Lago Maggiore - East Reverse",
  "Autodrome Lago Maggiore - Full Course",
  "Autodrome Lago Maggiore - Full Course Reverse",
  "Autodrome Lago Maggiore - West",
  "Autodrome Lago Maggiore - West End",
  "Autodrome Lago Maggiore - West End Reverse",
  "Autodrome Lago Maggiore - West Reverse",
  "Autodromo Nazionale Monza",
  "Autodromo Nazionale Monza No Chicane",
  "Autódromo de Interlagos",
  "Autopolis International Racing Course",
  "Autopolis International Racing Course - Short Course",
  "Blue Moon Bay Speedway",
  "Blue Moon Bay Speedway - Infield A",
  "Blue Moon Bay Speedway - Infield A Reverse",
  "Blue Moon Bay Speedway - Infield B",
  "Blue Moon Bay Speedway - Infield B Reverse",
  "Blue Moon Bay Speedway Reverse",
  "Brands Hatch Grand Prix Circuit",
  "Brands Hatch Indy Circuit",
  "BB Raceway",
  "BB Raceway Reverse",
  "Circuit Gilles-Villeneuve",
  "Circuit de Barcelona-Catalunya GP Layout",
  "Circuit de Barcelona-Catalunya GP Layout No Chicane",
  "Circuit de Barcelona-Catalunya National Layout",
  "Circuit de Barcelona-Catalunya Rallycross Layout",
  "Circuit de Sainte-Croix - A",
  "Circuit de Sainte-Croix - A Reverse",
  "Circuit de Sainte-Croix - B",
  "Circuit de Sainte-Croix - B Reverse",
  "Circuit de Sainte-Croix - C",
  "Circuit de Sainte-Croix - C Reverse",
  "Circuit de Spa-Francorchamps",
  "Spa 24h Layout",
  "Colorado Springs - Lake",
  "Colorado Springs - Lake Reverse",
  "Daytona Road Course",
  "Daytona Tri-Oval",
  "Deep Forest Raceway",
  "Deep Forest Raceway Reverse",
  "Dragon Trail - Gardens",
  "Dragon Trail - Gardens Reverse",
  "Dragon Trail - Seaside",
  "Dragon Trail - Seaside Reverse",
  "Eiger Nordwand",
  "Eiger Nordwand Reverse",
  "Fishermans Ranch",
  "Fishermans Ranch Reverse",
  "Fuji International Speedway",
  "Fuji International Speedway (Short)",
  "Goodwood Motor Circuit",
  "Grand Valley - Highway 1",
  "Grand Valley - Highway 1 Reverse",
  "Grand Valley - South",
  "Grand Valley - South Reverse",
  "High Speed Ring",
  "High Speed Ring Reverse",
  "Kyoto Driving Park - Miyabi",
  "Kyoto Driving Park - Yamagiwa",
  "Kyoto Driving Park - Yamagiwa Reverse",
  "Kyoto Driving Park - Yamagiwa+Miyabi",
  "Kyoto Driving Park - Yamagiwa+Miyabi Reverse",
  "Lake Louise Long Track",
  "Lake Louise Long Track Reverse",
  "Lake Louise Short Track",
  "Lake Louise Short Track Reverse",
  "Lake Louise Tri-Oval",
  "Lake Louise Tri-Oval Reverse",
  "Michelin Raceway Road Atlanta",
  "Mount Panorama Motor Racing Circuit",
  "Northern Isle Speedway",
  "Nürburgring 24h",
  "Nürburgring Endurance",
  "Nürburgring Endurance II",
  "Nürburgring GP",
  "Nürburgring Nordschleife",
  "Nürburgring Nordschleife Tourist",
  "Nürburgring Sprint",
  "Red Bull Ring",
  "Red Bull Ring Short Track",
  "Sardegna - Road Track - A",
  "Sardegna - Road Track - A Reverse",
  "Sardegna - Road Track - B",
  "Sardegna - Road Track - B Reverse",
  "Sardegna - Road Track - C",
  "Sardegna - Road Track - C Reverse",
  "Sardegna - Windmills",
  "Sardegna - Windmills Reverse",
  "Special Stage Route X",
  "Suzuka Circuit",
  "Suzuka Circuit East Course",
  "Tokyo Expressway - Central Clockwise",
  "Tokyo Expressway - Central Counterclockwise",
  "Tokyo Expressway - East Clockwise",
  "Tokyo Expressway - East Counterclockwise",
  "Tokyo Expressway - South Clockwise",
  "Tokyo Expressway - South Counterclockwise",
  "Trial Mountain Circuit",
  "Trial Mountain Circuit Reverse",
  "Tsukuba Circuit",
  "Watkins Glen Long Course",
  "Watkins Glen Short Course",
  "WeatherTech Raceway Laguna Seca",
  "Willow Springs International Raceway: Big Willow",
  "Willow Springs International Raceway: Horse Thief Mile",
  "Willow Springs International Raceway: Horse Thief Mile Reverse",
  "Willow Springs International Raceway: Streets of Willow Springs",
  "Willow Springs International Raceway: Streets of Willow Springs Reverse",
  "Yas Marina Circuit",
] as const;

export type GT7Track = typeof GT7_TRACKS[number];