export type PanelTypes =
  | "ACCOUNT"
  | "NOTIFICATIONS"
  | "PROFILES"
  | "SQUADS"
  | "LEAGUES"
  | "GUEST_PROFILES"
  | "GUEST_SQUADS"
  | "GUEST_LEAGUES"
  | "PROFILE_EDIT"
  | "PROFILE_FOLLOWERS"
  | "PROFILE_FOLLOWERS"
  | "SQUAD_EDIT"
  | "SQUAD_FOLLOWERS"
  | "SQUAD_MEMBERS"
  | "LEAGUE_FOLLOWERS"
  | "LEAGUE_JOIN"
  | "LEAGUE_PARTICIPANTS"
  | "BRIEFING"
  | "DRIVER_GRID"
  | "EVENT_SETTINGS"
  | "TRACK_CAR_DETAILS";
  

export type PanelProviderTypes = "none" | PanelTypes;
